# Generated by Django 3.0.3 on 2020-03-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godtk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='godtk',
            old_name='title',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='godtk',
            old_name='audience',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='godtk',
            old_name='title_en',
            new_name='event_title',
        ),
        migrations.RenameField(
            model_name='godtk',
            old_name='genre',
            new_name='event_url',
        ),
        migrations.RenameField(
            model_name='godtk',
            old_name='open_date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='godtk',
            name='poster_url',
        ),
        migrations.RemoveField(
            model_name='godtk',
            name='score',
        ),
        migrations.RemoveField(
            model_name='godtk',
            name='watch_grade',
        ),
        migrations.AddField(
            model_name='godtk',
            name='img_path',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='godtk',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
