# Generated by Django 3.0.3 on 2020-03-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godtk', '0003_auto_20200303_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='godtk',
            name='company_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='godtk',
            name='event_title',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
