# Generated by Django 3.0.3 on 2020-03-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godtk', '0005_auto_20200304_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='content',
            new_name='tag',
        ),
        migrations.AddField(
            model_name='godtk',
            name='tag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
