# Generated by Django 3.0.3 on 2020-03-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godtk', '0006_auto_20200305_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='godtk',
            name='img_path',
            field=models.ImageField(upload_to=''),
        ),
    ]
