# Generated by Django 3.0.3 on 2020-03-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godtk', '0007_auto_20200305_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='godtk',
            name='img_path',
            field=models.ImageField(upload_to='image'),
        ),
    ]
