# Generated by Django 3.0.3 on 2020-03-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godtk', '0008_auto_20200305_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='godtk',
            name='img_path',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
