# Generated by Django 3.0.3 on 2020-03-05 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('godtk', '0010_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
